from enum import Enum
from typing import TypedDict, List, Dict, Any

class AgentType(str, Enum):
    BILLING = "billing"
    SHIPPING = "shipping"
    REFUND = "refund"

class Task(TypedDict):
    id: str            # Unique task identifier (e.g. "task_0")
    agent: AgentType   # Target department
    instruction: str   # Clean instructions for the worker node
    status: str        # 'pending', 'completed', 'failed'

class TaskResult(TypedDict):
    task_id: str       # Reference to the executed Task ID
    agent: AgentType   # The department that executed the task
    status: str        # 'completed' or 'failed'
    summary: str       # High-level summary of the mock tool output and action
    detail: str        # Detailed draft response text generated by the worker

class AgentState(TypedDict):
    customer_request: str        # Raw customer query
    tasks: List[Task]            # Structured task plan generated by the Planner
    current_task_index: int      # Queue index pointer managed by the Dispatcher
    results: List[TaskResult]    # Ledger of execution results
    final_response: str          # Final synthesized output response
